### ISSUE TITLE
error bundle exec rake daemons:start

### ISSUE THREAD

**Issue by vitorgamer58** [Apollo-IT/peatio_current#1]
hey, i get this erro
```
deploy@vultr:~/peatio/current$ bundle exec rake daemons:start
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 60 was converted to "60". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 8080 was converted to "8080". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 499460 was converted to "499460". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 443 was converted to "443". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3820920586 was converted to "3820920586". (StructuredWarnings::StandardWarning)
/home/deploy/.rbenv/versions/2.2.8/lib/ruby/2.2.0/digest.rb:15:in `const_missing': library not found for class Digest::SHA1 -- digest/sha1 (LoadError)
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/2.2.0/digest.rb:99:in `block in Digest'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/2.2.0/digest.rb:97:in `synchronize'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/2.2.0/digest.rb:97:in `Digest'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:223:in `digest'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source/git.rb:286:in `uri_hash'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source/git.rb:320:in `git_scope'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source/git.rb:215:in `cache_path'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source/git.rb:298:in `git_proxy'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source/git.rb:224:in `revision'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source/git.rb:75:in `to_s'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source_list.rb:85:in `each'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source_list.rb:85:in `sort_by'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source_list.rb:85:in `lock_sources'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/source_list.rb:104:in `replace_sources!'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/definition.rb:667:in `converge_sources'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/definition.rb:120:in `initialize'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/dsl.rb:218:in `new'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/dsl.rb:218:in `to_definition'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/dsl.rb:13:in `evaluate'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/definition.rb:35:in `build'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler.rb:135:in `definition'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler.rb:101:in `setup'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/deploy/.rbenv/versions/2.2.8/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by shouton** [comment]
SHA1 is not found, please reinstall ruby lib step by step. 

It’s a long way to go, you’d better give up.

**Comment by vitorgamer58** [comment]
i get this now
```
deploy@vultr:~/peatio/current$ bundle exec rake daemons:start
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 60 was converted to "60". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 8080 was converted to "8080". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 499460 was converted to "499460". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 443 was converted to "443". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figa
```ro configuration. 3820920586 was converted to "3820920586". (StructuredWarnings::StandardWarning)

**Comment by Apollo-IT** [comment]
Hi. Thanks for your attentions.
I've upgraded ruby and rails versions.
Also Gem is updated and some issues are fixed.

please check latest [commit](https://github.com/Apollo-IT/peatio/commit/4286d83089ec32336bacfa9ce22bce7d30b3fa61)

This may has another issues during upgrade.
Please leave messages.
Thanks again.

**Comment by vitorgamer58** [comment]
i get this now
```
deploy@vultr:~/peatio/current$  bundle exec rake daemons:start
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 499460 was converted to "499460". (StructuredWarnings::StandardWarning)
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)
```

I restarted NGINX but the website does not work

**Comment by vitorgamer58** [comment]
I discovered that the problem is HTTPS, I still have no way to pass my certificate to VPS, I'm still in the testing phase, I tried to disable FORCE SSL inside `config/environments/production.rb` but when entering my domain I am redeemed to https and the secure connection fails

**Comment by Apollo-IT** [comment]
hi, This repository is WIP.
it's under upgrading.
It will be completed soon.
Until that, we can meet some issues.
