### ISSUE TITLE
Cannot run db:setup

### ISSUE THREAD

**Issue by glaksmono** [Apollo-IT/peatio_current#7]
I'm getting the following error:

```
➜  peatio_current git:(master) ✗ bundle exec rake db:setup
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /Users/glaksmono/Documents/peatio_current/config/application.rb:12)
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 510458 was converted to "510458". (StructuredWarnings::StandardWarning)/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'exchange_development.documents' doesn't exist: SHOW FULL FIELDS FROM `documents`
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `query'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute_and_free'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:463:in `columns'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/attributes.rb:93:in `columns'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/attribute_methods/serialization.rb:62:in `serialized_attributes'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:54:in `enable_serializable_attribute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:32:in `block in allow_translation_of_attributes'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:30:in `each'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:30:in `allow_translation_of_attributes'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:13:in `translates'
/Users/glaksmono/Documents/peatio_current/app/models/document.rb:3:in `<class:Document>'
/Users/glaksmono/Documents/peatio_current/app/models/document.rb:1:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:457:in `load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:457:in `block in load_file'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:647:in `new_constants_in'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:456:in `load_file'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:354:in `require_or_load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:471:in `each'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:471:in `block in eager_load!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:469:in `each'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:469:in `eager_load!'
/Users/glaksmono/Documents/peatio_current/config/routes.rb:1:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:40:in `each'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:16:in `reload!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/file_update_checker.rb:75:in `execute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:27:in `updater'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/Users/glaksmono/Documents/peatio_current/config/environment.rb:5:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Mysql2::Error: Table 'exchange_development.documents' doesn't exist
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `query'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/mysql2_adapter.rb:225:in `execute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute_and_free'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:463:in `columns'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/attributes.rb:93:in `columns'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.8/lib/active_record/attribute_methods/serialization.rb:62:in `serialized_attributes'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:54:in `enable_serializable_attribute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:32:in `block in allow_translation_of_attributes'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:30:in `each'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:30:in `allow_translation_of_attributes'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/globalize-4.0.3/lib/globalize/active_record/act_macro.rb:13:in `translates'
/Users/glaksmono/Documents/peatio_current/app/models/document.rb:3:in `<class:Document>'
/Users/glaksmono/Documents/peatio_current/app/models/document.rb:1:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:457:in `load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:457:in `block in load_file'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:647:in `new_constants_in'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:456:in `load_file'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:354:in `require_or_load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:471:in `each'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:471:in `block in eager_load!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:469:in `each'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/engine.rb:469:in `eager_load!'
/Users/glaksmono/Documents/peatio_current/config/routes.rb:1:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:40:in `each'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:16:in `reload!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/file_update_checker.rb:75:in `execute'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:27:in `updater'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/Users/glaksmono/Documents/peatio_current/config/environment.rb:5:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/glaksmono/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)
```

Thoughts?

**Comment by Nolaan** [comment]
Same here, aren't we supposed to populate the database first with some schema?

**Comment by santoshJAVA** [comment]
Same Here.please help

**Comment by pradeep-systango** [comment]
I am facing the same issue. Please help.

**Comment by pradeep-systango** [comment]
Hi All, I have figured out the problem here.
This error is because of 
`translates *TRANSLATABLE_ATTR`
line in document.rb file

Steps to run the migrate command successfully:
Step-1: Comment 'translates *TRANSLATABLE_ATTR' line
Step-2: Run the migration command
Step-3: After some migration running successfully you will see another error that is because we have commented this line. Don't worry. Now Uncomment this line.
Step-4: run migrate command again

You should successfully be able to setup this project now.

Please let

**Comment by cryptobrokerage** [comment]
Hi Pradeep,   
where did you locate the file to comment out 
Step-1: Comment 'translates *TRANSLATABLE_ATTR' line

**Comment by cryptobrokerage** [comment]
\\i tried a find documet.rb and could not find file.
Also tried to locate on git hub.
Where was your document.rb

**Comment by cryptobrokerage** [comment]
I agree.  It would be a very big help.
I have been working on this exchange from some time with some hope the open community would help.  I now can see the befits of white label solutions over open source.

Your steps to resolved the issue most people seems to be is

Steps to run the migrate command successfully:
Step-1: Comment 'translates *TRANSLATABLE_ATTR' line
Step-2: Run the migration command
Step-3: After some migration running successfully you will see another error that is because we have commented this line. Don't worry. Now Uncomment this line.
Step-4: run migrate command again

More info for Step 1: Can you please let us know where to locate the line you said to commit out
More info forStep 2:  The command to run will be helpfully to confirm user is running correct command

Thank you for your help and we await your reply.   Can you also confirm if you are now running in a production environment.  If so are you hosting yourself or with a 3rd party like AWS.

**Comment by pradeep-systango** [comment]
the document.rb file is inside models directory.
The line no. 3 which have the following code on that line
`translates *TRANSLATABLE_ATTR`
Comment that line

Run
rake db:create
rake db:migrate

After some migration running successfully you will see another error that is because we have commented that line. Don't worry. Now Uncomment that line and

rake db:migrate

Now you should be good to go.

**Comment by cryptobrokerage** [comment]
Thanks @pradeep-systango  That helped and now its is working.

I have another issue
When i load local host i am getting to some type of page which also has console input ability.

ActivRecord:pendingMigrationWeeor at/
Migration are pending. To resolve this issue run:
bin/rake db:migrate Rails_env=development 

I ran both commands in browser and terminal but no luck.
Could anyone help

**Comment by cryptobrokerage** [comment]
issue seems to be with 

lib.middlewre/il8n_js.rb
line 9
@app.call(env)

Anyone else having this issue

**Comment by cryptobrokerage** [comment]
issue was resolved.
Had to go back and uncommit what was comiited out and re run which was said.
My mistake
Thanks @pradeep-systango
